### ISSUE TITLE
Меню Filter на странице catalog.html не закрывается

### ISSUE THREAD

**Issue by dp140482** [ambernou/professional_layout#3]
Всё из-за того, что само меню вызывается как содержимое details. Для его закрытия необходимо нажать на заголовок details, но он скрыт смещённым при помощи position: absolute; top: -13px; меню.

Решение:

Внешнюю часть меню с чёрным заголовком Filter выполнить в виде `<div class="filter-menu">`. `<summary>` тоже превратить в div или какой-нибудь заголовок. Если оставить внешний details, то работать будет плохо: после первого нажатия на чёрный заголовок невидимо откроется этот самый details, и только со второго клика появится меню. Это неправильно. В самом появляющемся меню id следует назначать самому внешнему div. Например, назначить id="filterMenuHead". Вложенной в него ссылке, обрамляющей розовый заголовок Filter, следует присвоить onclick="closeFilterMenu()". Обрамляющий чёрный заголовок Filter div должен быть оснащён onclick="openFilterMenu()". Ну, и javascript:

        function closeFilterMenu() {
            document.getElementById("filterMenuHead").style.visibility = "hidden";
        }

        function openFilterMenu() {
            document.getElementById("filterMenuHead").style.visibility = "visible";
        }

Именно так, при помощи свойства видимости. Это решение работает.

**Comment by ambernou** [comment]
great!
